name: Nuitka Release
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository content
        uses: actions/checkout@v2
        
      - name: Setting up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
        
      - name: Set up GCC for compilation
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
        
      - name: Installing Python packages
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install nuitka
            
      - name: Compiling the package with nuitka
        run: |
            python -m nuitka --module animdl
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: './animdl.dist/'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          prerelease: true
          tag: 1.3-auto
          token: ${{ secrets.GITHUB_TOKEN }}

        
